### ISSUE TITLE
Missing Azure Cloud Integration Documentation

### ISSUE THREAD

**Issue by CalvinHartwell** [charmed-kubernetes/kubernetes-docs#180]
Hi all, 

I noticed that the official documentation does not include the steps for integrating CDK with Azure like it does for AWS and GCP though this is possible today. We need to document this for customers. 

Link: [https://www.ubuntu.com/kubernetes/docs](https://www.ubuntu.com/kubernetes/docs)

Cheers

- Calvin

**Comment by evilnick** [comment]
Yup, there is a card for this in the backlog currently https://trello.com/c/XwOBnfO5/81-cdk-on-azure
