### ISSUE TITLE
Missing VMware Cloud Integration Documentation

### ISSUE THREAD

**Issue by CalvinHartwell** [charmed-kubernetes/kubernetes-docs#181]
Hi all,

I noticed that the official documentation does not include the steps for integrating CDK with VMware like it does for AWS and GCP though this is possible today. We need to document this for customers.

Link: [https://www.ubuntu.com/kubernetes/docs](https://www.ubuntu.com/kubernetes/docs)

Cheers

Calvin

**Comment by evilnick** [comment]
This is also in the backlog. If it helps, both these integrator pages are next after work on configuring networking (also something possible today) is complete
