### ISSUE TITLE
Make Reporting and Updating Incorrect Documentation Easier

### ISSUE THREAD

**Issue by CalvinHartwell** [charmed-kubernetes/kubernetes-docs#182]
Hi all,

Currently there is no easy way for customers to report errors and issues on the upstream Kubernetes documentation found here: [https://www.ubuntu.com/kubernetes/docs](https://www.ubuntu.com/kubernetes/docs). Can we update the documentation site so that users can report problems or fork and update the documentation in a easy way similar to the upstream Kubernetes documentation? 

Customers may also want to contribute additional or missing documentation.

Cheers,

- Calvin

**Comment by evilnick** [comment]
The get in touch page ( https://www.ubuntu.com/kubernetes/docs/get-in-touch) has a link to this repo, which is where users/customers can currently add issues or submit changes to docs.

If you have any suggestions on where else this information should be added, please let me know

**Comment by hyperbolic2346** [comment]
I was heading here to post this issue and found this one. It would be nice to have a link on each page "Help improve these docs" that would link back to the source for easy editing. This is done on the kubernetes.io docs with a pencil icon at the top and things like MaaS docs with a link at the bottom. A direct link to the page the user is reading allows them to edit or ask relevant questions that aren't answered easily.

**Comment by evilnick** [comment]
Belated update - In addition to get in touch there is now a link in the footer of each page to submit issues or raise a pr on docs (edit this page) so I'm closing this. Please reopen if this doesn't solve the issue
