### ISSUE TITLE
call out that redeploy of kube-dns / core-dns can cause permanent DNS resolution problems for existing pods

### ISSUE THREAD

**Issue by jayk-canonical** [charmed-kubernetes/kubernetes-docs#265]
When there are issues with kube-dns (and probably core-dns) deployments, one of the side effects is that the kubernetes service for DNS resolution can be destroyed and recreated.

When this happens, it is assigned a new IP address.  Because the Service IP is provided to pods at pod startup time, this means that any pods started prior to this occurring will be stuck trying to resolve against the previous DNS service IP, which no longer exists.

These pods can not recover and need to be terminated and restarted in order for them to be able to become attached to the new DNS service IP.  

This is a rather significant issue as a kube-dns redeploy means effectively every POD in the cluster must be restarted.  This should be called out in the documentation (probably in 'upgrades' and/or kube-dns sections), so that people can plan around it and/or know what action to take when their pods suddenly can't resolve anything.

**Comment by evilnick** [comment]
Thanks for the info, I will have a look
