### ISSUE TITLE
Admission control Q&A

### ISSUE THREAD

**Issue by tvansteenburgh** [charmed-kubernetes/kubernetes-docs#269]
Q: How do I enable additional admission controls on my cluster?
A: Additional admission controls can be enabled by setting `api-extra-args` on the kubernetes-master application. For example, to enable the `PodSecurityPolicy` admission controller:

First, take note of the current value of `api-extra-args`:
```bash
juju config kubernetes-master api-extra-args`
```

Then update the value of `api-extra-args` to include the new admission controller:

On 1.16 and higher (todo: include master charm rev here):
```bash
juju config kubernetes-master api-extra-args="enable-admission-plugins=PodSecurityPolicy"
```

On 1.15 and earlier (todo: include master charm rev here):
```bash
juju config kubernetes-master api-extra-args="admission-control=PodSecurityPolicy"
```

**Comment by hyperbolic2346** [comment]
Note that admission-control and enable-admission-plugins are mutually exclusive and at some point after revision 724 of kubernetes-master we have merged https://github.com/charmed-kubernetes/charm-kubernetes-master/pull/55, which has default enable-admission-plugins.
