### ISSUE TITLE
Link bundle readmes to official docs

### ISSUE THREAD

**Issue by tvansteenburgh** [charmed-kubernetes/kubernetes-docs#294]
We need to remove most of the "doc" material from the bundle readmes (e.g. https://jaas.ai/charmed-kubernetes) and instead point the reader to the official docs (ubuntu.com/kubernetes/docs).

The readmes are not as well-maintained, which can lead to confusion when the readme has different (or missing) information compared to the docs (see https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1846514 for an example).

Before deleting all the readme content, we should move the good stuff into the official docs.

**Comment by tvansteenburgh** [comment]
Another example here: https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1846670

**Comment by evilnick** [comment]
See #296
