### ISSUE TITLE
tutorial stops working after juju scp

### ISSUE THREAD

**Issue by DraconPern** [charmed-kubernetes/kubernetes-docs#301]
for This line 
`juju scp kubernetes-master/0:config ~/.kube/config`
 I got
`ERROR exit status 1 (scp: config: No such file or directory)` And I couldn't go any farther.  Ubuntu 18.04

**Comment by hyperbolic2346** [comment]
Was your cluster up and stable? Until things settle the config file will not be available.

**Comment by DraconPern** [comment]
Ah.  Thanks, it wasn't stable yet.  Might be good to add some instruction about the status since the tutorial doesn't mention it at that point.
