### ISSUE TITLE
Multi-network configuration appears to be missing

### ISSUE THREAD

**Issue by CalvinHartwell** [charmed-kubernetes/kubernetes-docs#304]
Hi all, 

As per the old wiki:

[https://github.com/charmed-kubernetes/bundle/wiki/Using-multiple-networks-with-CDK](https://github.com/charmed-kubernetes/bundle/wiki/Using-multiple-networks-with-CDK)

This configuration appears to be missing from the new manual, can we please update and add it? 

Cheers

**Comment by tvansteenburgh** [comment]
@Cynerva Would you mind taking a stab at this?
