### ISSUE TITLE
couple issues in the graylog section of the logging page

### ISSUE THREAD

**Issue by kwmonroe** [charmed-kubernetes/kubernetes-docs#308]
https://ubuntu.com/kubernetes/docs/logging

- Seems to be a broken `quickstart` link:

```
See the [quickstart guide][quickstart] for more details on installing Charmed Kubernetes.
```

- The reverse proxy template should look like this:

https://raw.githubusercontent.com/charmed-kubernetes/kubernetes-docs/master/assets/graylog-vhost.tmpl

```
<Location "/">
    RequestHeader set X-Graylog-Server-URL "http://{{servername}}/"
    ProxyPass http://{{graylog_web}}/
    ProxyPassReverse http://{{graylog_web}}/
</Location>
```

In the rendered page, however, none of the `{{ foo }}` text is coming through.

**Comment by evilnick** [comment]
There are some issues with different processing of markdown due to different engines being used, off the top of my head I imagine it is something to do with that. Thanks for the highly informative report, I will see what can be done
