### ISSUE TITLE
e2e testing link broken

### ISSUE THREAD

**Issue by jlosito** [charmed-kubernetes/kubernetes-docs#309]
The link to Kubernetes upstream documentation for end-to-end testing in broken under the "Running specific tests" section of the [validation page](https://ubuntu.com/kubernetes/docs/validation).

**Comment by evilnick** [comment]
Many thanks for reporting this, will fix it as soon as we find where upstream moved the page to!

**Comment by evilnick** [comment]
Ah, I see its moved into a SIG. Will update the page, but the link if you didn't find it is: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md
