### ISSUE TITLE
Linking to section headings

### ISSUE THREAD

**Issue by tvansteenburgh** [charmed-kubernetes/kubernetes-docs#314]
It would be nice to be able to link directly to a heading in a page. Is this something that can be added to our page generation (adding anchor tags to headings)?

**Comment by evilnick** [comment]
It would be! Unfortunately, while it works on the test site, at the moment neither ubuntu.com or any of the discourse driven sites generate ids from headings. I have been adding them manually where needed. I thought there was a bug about this (I certainly remember discussing it at least twice with web-team) so I will follow up with them.

In the meantime, if there are specific headers that you would like to link to, let me know

**Comment by evilnick** [comment]
(for discourse, see https://github.com/canonical-webteam-archive/docs.snapcraft.io/issues/33)
