### ISSUE TITLE
Add-ons Q&A

### ISSUE THREAD

**Issue by tvansteenburgh** [charmed-kubernetes/kubernetes-docs#316]
Q: "How do I enable/disable x?"

Example of this here: https://discourse.jujucharms.com/t/how-to-disable-monitoring-influxdb-grafana-addon-in-k8s/2298/2

But we should probably have a section for add-ons that explains how they work in general (auto-applied by CDK, can't be modified, etc), and how to enable/disable each one.

**Comment by evilnick** [comment]
Yes, I agree - I think this is a great example of what I wanted to include in the FAQ pages I mentioned
