### ISSUE TITLE
Private Docker Registry page incorrectly suggests that docker-registry and kubernetes-worker should be related

### ISSUE THREAD

**Issue by Cynerva** [charmed-kubernetes/kubernetes-docs#318]
From https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1851638:

> However maybe the documentation (https://ubuntu.com/kubernetes/docs/docker-registry) should be updated because under "Docker on Kubernetes workers it is stated: "Docker on the Kubernetes workers needs to talk to the registry securely. By relating docker-registry and kubernetes-worker, appropriate certificates are added to /etc/docker/certs.d on all workers." This is why I tried to relate the kubernetes-worker and docker-registry charms.

As of Charmed Kubernetes 1.16, the relation between kubernetes-worker and docker-registry no longer exists. The registry should be related to containerd or docker instead.

**Comment by evilnick** [comment]
thanks
