### ISSUE TITLE
snap "client-keystone-auth" can't be installed

### ISSUE THREAD

**Issue by grebennikov** [charmed-kubernetes/kubernetes-docs#334]
The instruction says:
"You will need to install the Keystone client. This can be done by running:
 sudo snap install client-keystone-auth"

However this is the output from the real environment:
error: snap "client-keystone-auth" is not available on stable but is available to install on the
       following channels:

       edge       snap install --edge client-keystone-auth

**Comment by cjohnston1158** [comment]
https://ubuntu.com/kubernetes/docs/ldap

**Comment by evilnick** [comment]
https://github.com/canonical-web-and-design/ubuntu.com/pull/8767
