### ISSUE TITLE
cannot set keystone policy for kubernetes master following the guide

### ISSUE THREAD

**Issue by grebennikov** [charmed-kubernetes/kubernetes-docs#335]
The guide says
When authorisation is enabled, the policy is defined in the configuration. A new policy can be applied by running:

juju config kubernetes-master keystone-policy=$(cat policy.yaml)

However if running this:
# juju config kubernetes-master keystone-policy=$(cat policy.yaml)
ERROR cannot set and retrieve values simultaneously

**Comment by Cynerva** [comment]
It should work with quotes:

```
juju config kubernetes-master keystone-policy="$(cat policy.yaml)"
```
