### ISSUE TITLE
Move Supported Versions page from wiki

### ISSUE THREAD

**Issue by tvansteenburgh** [charmed-kubernetes/kubernetes-docs#339]
Let's move this page into the Reference section of the docs:

https://github.com/charmed-kubernetes/bundle/wiki/Supported-Kubernetes-Versions

I discovered today that this wiki page is being linked to from https://ubuntu.com/legal/ubuntu-advantage-service-description#uasd-support-levels, which I'd like to change.

**Comment by evilnick** [comment]
updated on ubuntu.com now
