### ISSUE TITLE
Kubernetes Ingress Page not found, 404! 

### ISSUE THREAD

**Issue by mehdiMj-ir** [charmed-kubernetes/kubernetes-docs#348]
Hi there, thanks for this useful documentation. at the end of this page, In "Clean up example
"  section, "To learn more about [Kubernetes Ingress](https://kubernetes.io/docs/user-guide/ingress.html) and how to configure the Ingress Controller beyond defaults" leads to nowhere and this page does not exist! 
I searched on official k8s site and I think the correct link is [ingress-controller ](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/)
hope it helps ;)

**Comment by evilnick** [comment]
Many thanks for pointing this out, I guess the upstream docs shuffled their pages around as I promise we do link check all the pages when we make them live. I found the correct link and I'll fix it up
