### ISSUE TITLE
Setting port for keepalived not really needed

### ISSUE THREAD

**Issue by jlosito** [charmed-kubernetes/kubernetes-docs#395]
The followed page tells us to set the port for the keepalived charm when setting up HA, but it may not be really necessary since the default value for the option is already 443.

https://ubuntu.com/kubernetes/docs/keepalived

```
$  juju config keepalived port=443
WARNING the configuration setting "port" already has the value "443"
```

**Comment by evilnick** [comment]
Thanks for reporting this (and the fix). I'm trying to work out why this didn't happen previously (and whether that may have an impact on anything else).

**Comment by jlosito** [comment]
It also looks like this is stated on the README of the charm. If we decide that we should remove this statement, we should probably go ahead and remove it from the README as well for consistency.

**Comment by evilnick** [comment]
yup, will do, thanks again
