### ISSUE TITLE
bad {{ }} render on the k8s logging page

### ISSUE THREAD

**Issue by kwmonroe** [charmed-kubernetes/kubernetes-docs#399]
3/4 of the way down the logging page, we tell people about an apache template to configure for the graylog interface. I'd link to an actual anchor, but that's apparently web 4.0 and we're not ready for that yet.  Search for `Location` to see where I mean:

https://ubuntu.com/kubernetes/docs/logging

That rendered block has a URL of `http:///`.  That should be `http://{{servername}}/` to match the thing we tell people [to download](https://raw.githubusercontent.com/charmed-kubernetes/kubernetes-docs/master/assets/graylog-vhost.tmpl).

**Comment by evilnick** [comment]
i swear I already fixed this once. thanks
