### ISSUE TITLE
kubernetes-master docs missing some actions

### ISSUE THREAD

**Issue by Cynerva** [charmed-kubernetes/kubernetes-docs#400]
Looking at https://ubuntu.com/kubernetes/docs/1.18/charm-kubernetes-master

The charm has 8 actions, but only 2 are documented.

This originates from https://bugs.launchpad.net/charm-kubernetes-master/+bug/1874145 in which it was reported against the charm's README.

**Comment by evilnick** [comment]
Fixed, at some point!
