### ISSUE TITLE
kubernetes-worker docs missing some actions

### ISSUE THREAD

**Issue by Cynerva** [charmed-kubernetes/kubernetes-docs#401]
Looking at https://ubuntu.com/kubernetes/docs/1.18/charm-kubernetes-worker

The charm has 5 actions, but only 2 are documented.

This originates from https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1874146 in which it was reported against the charm's README.

**Comment by evilnick** [comment]
Fixed
