### ISSUE TITLE
ERROR no API addresses

### ISSUE THREAD

**Issue by sachithmuhandiram** [charmed-kubernetes/kubernetes-docs#403]
I have tried to install Charmed Kubernetes as described [here](https://ubuntu.com/kubernetes/docs/install-local) in CentOS-7 environment with the help of `snap`.

`sudo snap install lxd`

`/snap/bin/lxd init`

Configured as described, without `ipv6` and with `dir` storage.

`sudo snap install juju --classic`

`juju bootstrap localhost` 

`juju add-model k8s`

> ERROR opening API connection : no API addresses

`juju version -> 2.7.6-centos7-amd64`

**Comment by sachithmuhandiram** [comment]
I suspect this occurred with network connection issue. As I have reinstalled Charmed-Kubernetes and then ran 
```
sudo snap install juju --classic
juju bootstrap localhost
juju add-model k8s
```
Without reproducing the Error.

So if you get this issue, please try reinstalling with a healthy internet connection.

**Comment by evilnick** [comment]
thanks for reporting it anyhow, let us know if you have further issues
