### ISSUE TITLE
Namespace of openstack-charmers-next shouldn't be used

### ISSUE THREAD

**Issue by pmatulis** [charmed-kubernetes/kubernetes-docs#413]
Unless for a very good reason the charm namespace of `openstack-charmers-next` (equivalent to a charm's master branch) should not be used in stable documentation. It is used four times in this doc set.

**Comment by evilnick** [comment]
I believe this relates to the vault charm, and the very good reason was the stable version didn't work, but I'm not sure if that remains true. @johnsca?

**Comment by johnsca** [comment]
Yeah, this is a hold-over from when Vault support was first added and some changes were needed to support K8s.  It can be changed now.

**Comment by evilnick** [comment]
@johnsca thanks, I'll fix those pages

**Comment by evilnick** [comment]
probably more important to fix the overlays - https://github.com/charmed-kubernetes/bundle/pull/778
