### ISSUE TITLE
No VMware vSphere integration page

### ISSUE THREAD

**Issue by nobuto-m** [charmed-kubernetes/kubernetes-docs#419]
Under the "Cloud Integration" section, there are dedicated pages for each cloud provider integration. However, there is no page about VMware vSphere integration.

![Screenshot from 2020-06-12 14-14-10](https://user-images.githubusercontent.com/4356209/84467426-120c2580-acb7-11ea-8908-07be51e27019.png)

**Comment by Cynerva** [comment]
Thanks for the report. There is an open issue for this already, please see https://github.com/charmed-kubernetes/kubernetes-docs/issues/181

I'm closing this one as a duplicate.
