### ISSUE TITLE
Support versions out of sync

### ISSUE THREAD

**Issue by chris-sanders** [charmed-kubernetes/kubernetes-docs#479]
The Ubuntu Release Cycle lists the supported versions for all products, including k8s: https://ubuntu.com/about/release-cycle

```
Kubernetes 1.19    Aug 2020    Jun 2021
Kubernetes 1.18    Mar 2020    Feb 2021
Kubernetes 1.17    Jan 2020    Dec 2020
Kubernetes 1.16    Oct 2019    Jul 2020
```

The documentation page https://ubuntu.com/kubernetes/docs/supported-versions seems to be behind and is contradictory to the official life-cycle. The immediate issue to to get these into sync to avoid confusion, more long term maybe the Kubernetes docs can describe the support cycle but defer the official dates for support to the ubuntu release-cycle page so there is 1 source of truth to avoid a mismatch every time the documents fall behind the release?

**Comment by evilnick** [comment]
Thanks. We did adjust the release-cycle page to reflect the reality of the delayed upstream release.

The published docs however, are at the moment correct. the latest supported version is 1.18. We are expecting charmed-kubernetes 1.19 to be released imminently, at which point the kubernetes docs will be updated.

**Comment by chris-sanders** [comment]
I'm not sure I follow. You say the published docs are correct.

Currently it states: Supported releases: 1.18.x, 1.17.x, 1.16.x
To my understanding 1.16.x is not currently supported.

**Comment by evilnick** [comment]
Yes. the published docs are currently correct.
The latest stable release of charmed-kubernetes is 1.18
Therefore, by our own policy of supporting the latest three releases, 1.18,1.17 and 1.16 are currently supported versions of Charmed Kubernetes. But it probably won't be tomorrow

In the wider context, the release schedule and the docs have been in alignment. The current situation, where there was a delay to the upstream release, and a wider gap between the upstream release and the consequent stable release of charmed kubernetes hasn't happened before, and hopefully won't happen again. When the release happens I will look at the release cycle table and update it, but currently I don't know whether to put September or October on it.
