### ISSUE TITLE
Add a note about insecure registries?

### ISSUE THREAD

**Issue by hyperbolic2346** [charmed-kubernetes/kubernetes-docs#486]
I found [this blog](https://ubuntu.com/blog/private-docker-registries-and-the-canonical-distribution-of-kubernetes) about insecure registries, but I believe that is dated now with the containerd subordinate. Looking at the containerd charm, there is the custom registries configuration and I think that will get me there, but my first look was [here](https://ubuntu.com/kubernetes/docs/docker-registry). Maybe some information about how to handle insecure registries for both docker and containerd subordinates is in order here?

**Comment by adam-stokes** [comment]
@hyperbolic2346 we'll see you at work bright and early Monday morning :)

**Comment by hyperbolic2346** [comment]
@adam-stokes I knew you missed me

**Comment by evilnick** [comment]
@hyperbolic2346 thanks 
I added a note to the top of the blog so that hopefully won't confuse people in future.
I agree that all the registry-related docs could do with a re-org (see #442) but I will leave this one open until the insecure aspect is addressed specifically.
