### ISSUE TITLE
Add a note about user created definitions

### ISSUE THREAD

**Issue by chris-sanders** [charmed-kubernetes/kubernetes-docs#496]
Users aren't always clear about what charmed Kubernetes handles during an upgrade. An example of this is [This cinder-csi-bug](https://bugs.launchpad.net/cdk-addons/+bug/1851255).

In this case it appears a StorageClass was created by an admin which charmed Kubernetes wasn't aware of and is not responsible for updating/upgrading. To address this generically for any given object, we could make it clear that charmed Kubernetes does not upgrade/modify any objects that it did not create. This would cover StorageClasses as the above example, but would be generic enough to cover *any* user modifications.

I'm not sure where it's easiest to include, maybe in the "Before you begin" section of the upgrade documents?

**Comment by evilnick** [comment]
Yes, that's a good point. I will word something appropriate and mark it for inclusion on all the versioned upgrade pages, and have a think about where else it may go
