### ISSUE TITLE
Upgrade docs could be more clear

### ISSUE THREAD

**Issue by cjohnston1158** [charmed-kubernetes/kubernetes-docs#502]
Currently the docs regarding upgrades aren't very clear. When upgrading a minor release the docs say:

> Once the desired version has been configured, the upgrades should be performed. This is done by running the upgrade action on each master unit in the cluster:
>
> juju run-action kubernetes-master/0 upgrade
> juju run-action kubernetes-master/1 upgrade
>
> If you have more master units in your cluster, you should continue and run this process on every one of them.

Based on this, I can't tell if I should upgrade one at a time or all at once. The fact that there is no break between the upgrade command on /0 vs /1 would lead me to believe that they should all be done at once.

This is the same on the in-place upgrade for the workers.

**Comment by chris-sanders** [comment]
I'll add to this that while we have a pause action, we don't tell people about it during this upgrade only during the series upgrade. I guess the assumption is that the snap upgrades are fast and the series is slow so you need to evacuate.

While discussing the impact as Chris suggests it's probably worth telling people that the pause action can be used if they would like to drain the node before upgrading. That's an optional step, and while I don't want to make it confusing it probably would fit well in any discussion of downtime from the upgrade commands.

**Comment by chris-sanders** [comment]
After further discussions, it seems we're _at least mostly_ confident that the containers will run through an in-place upgrade. That being the case, we should just say so in the docs and skip the whole 'pause' discussion.

**Comment by johnsca** [comment]
While I think the underlying containers would continue to run, it is possible for inter-pod or ingress communication to be interrupted when kube-proxy restarts, but I'm not certain and that might depend on the CNI being used.

**Comment by evilnick** [comment]
Okay, so now this seems only slightly more clear to me. I can for sure add a comment saying that in-place upgrades for the master and workers are fine, and remove the whole blue-green section, but it still seems vague to me what if any interruption to services a user could expect.

**Comment by evilnick** [comment]
Ah okay, so it is only the in-place which may need a comment. We still need to know what the potential interruption is

**Comment by Cynerva** [comment]
I think if all masters/workers are upgraded at the same time, we should assume that the Kubernetes services (kube-apiserver, kube-controller-manager, kube-scheduler, kubelet, kube-proxy) may be temporarily offline on all units at the same time.

We can test what happens in that scenario with:

```
juju run --application kubernetes-master 'for snap in kube-apiserver kube-controller-manager kube-scheduler kube-proxy; do snap stop $snap; done'
juju run --application kubernetes-worker 'for snap in kubelet kube-proxy; do snap stop $snap; done'
```

I did this against a standard Charmed Kubernetes cluster and observed the following interruptions:
1. The Kubernetes API was unavailable.
2. My `kubectl exec` and `kubectl logs` sessions were also terminated.
3. Other consequences you might expect from the control plane being down. Pods will not be scheduled or rescheduled. Liveness and readiness probes will not occur.

Things that were NOT interrupted:
1. Containers were not halted or restarted.
2. NodePort services were still reachable and serving responses.
3. Ingress endpoints were still reachable and serving responses.
4. Pods could still communicate with eachother by Service Cluster IPs.
5. Pods could still resolve DNS for internal resources (e.g. `kubernetes.default.svc.cluster.local`).
6. Pods could still resolve DNS for external resources (e.g `www.google.com`).

Some things I did not test:
1. LoadBalancer services.
   * These use NodePorts behind the scenes so I would still expect these to work.
2. Cloud integrators.
3. Other integrations like keystone, ceph, etc.
4. Anything related to ipv6.

In general I would say that upgrading the units together may lead to a temporary disruption of the Kubernetes control plane. Most workloads will not be impacted, however there may be some disruption to workloads that rely on direct communication with the Kubernetes API, e.g. kubernetes-dashboard.

> While I think the underlying containers would continue to run, it is possible for inter-pod or ingress communication to be interrupted when kube-proxy restarts, but I'm not certain and that might depend on the CNI being used.

Stopping kube-proxy usually isn't as disruptive as it might seem. In the default iptables proxy mode, even when kube-proxy is down, the iptables rules are still there and able to proxy traffic. It might be more disruptive when kube-proxy is configured with proxy-mode=userspace which is what we recommend on LXD. I think kube-proxy might handle ipv6 traffic a bit differently, so it's possible ipv6 traffic might be disrupted in a way that ipv4 is not.

It generally shouldn't matter which CNI is used. One possible risk when running Calico/Canal is that the calico-kube-controllers pod, which determines network policies, might be disrupted when it's unable to reach the Kubernetes API. However, I ran the tests above on a cluster with Canal and saw the same results as I did on Flannel, so I think calico-kube-controllers is smart enough to handle it.
