### ISSUE TITLE
Upgrading references old versions

### ISSUE THREAD

**Issue by chris-sanders** [charmed-kubernetes/kubernetes-docs#503]
On the upgrade pages like https://ubuntu.com/kubernetes/docs/1.19/upgrading while the page is specifically about upgrading to 1.19 the examples tell people to choose their version and then use examples of 1.10 and 1.12. 

I'm not sure how this is being generated, is it possible to make this a variable or reference of some kind? For users wanting to upgrade to 1.19 it would really be best to remove any choose your own adventure and just tell them to set it to 1.19.

**Comment by evilnick** [comment]
Yeah, it comes from a template, I can insert the current version instead

**Comment by evilnick** [comment]
this went live with 1.20
