### ISSUE TITLE
Simple master-worker cluster using two virtual-machines

### ISSUE THREAD

**Issue by partha-kaushik** [charmed-kubernetes/kubernetes-docs#516]
I believe that a "simple one master node plus one worker node" cluster using two virtual-machines would be a very popular option for people to experiment with and learn K8S.  The VMs can be anywhere, no cloud affiliation. Some docs and support for this scenario will be helpful.

**Comment by chris-sanders** [comment]
If you're not yet ready to be opinionated about the Kubernetes configuration I think you might be better served by https://microk8s.io/

While you can scale a bundle down to a minimal install, I don't know that specifically maintaining a 1 master and 1 worker bundle adds a lot of value. You can use https://jaas.ai/charmed-kubernetes and modify your deployment to reduces masters/workers if that is your use case. Others may want to change the CNI or make other modifications. The bundles provide an example, and you're intended to compose the Kubernetes that fits your specific needs. However, if just staring with Kuberentes I think microk8s is a good start and both Microk8s and Charmed Kubernetes support the same upstream binaries meaning you can expand with either product as you learn.
