### ISSUE TITLE
Confusing upgrade instructions for 1.20

### ISSUE THREAD

**Issue by cjohnston1158** [charmed-kubernetes/kubernetes-docs#536]
https://ubuntu.com/kubernetes/docs/1.20/upgrading

The upgrade instructions specific for 1.20 state:

> So, for example, to select the stable 1.19 version of Kubernetes, you would enter:

`juju config kubernetes-master channel=1.18/stable`

> If you wanted to try a release candidate for 1.20, the channel would be 1.20/candidate

It's quite confusing that the docs list 3 different versions, with mismatched references, and 1.20 as candidate.

**Comment by evilnick** [comment]
Thanks, I believe all the upgrade docs are right now
