### ISSUE TITLE
When deploying local kubernetes cluster, kurbernetes-worker nodes miss ephemeral storage

### ISSUE THREAD

**Issue by MatthijsKrempel** [charmed-kubernetes/kubernetes-docs#539]
Hi,

I'm trying to get started with Charmed Kubernetes and followed your local installation guide from here;

https://ubuntu.com/kubernetes/docs/install-local

The kubernetes-master node is stuck in waiting for "Waiting for 3 kube-system pods to start".
And that's to be expected because the kubernetes-worker nodes are NotReady.

When I use describe on one of the nodes, this message shows up constantly;

Warning  InvalidDiskCapacity      12s    kubelet     invalid capacity 0 on image filesystem

When I ssh into that worker and run a disk check;

Filesystem                         Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--vg-ubuntu--lv   62G   31G   28G  53% /
none                               492K  4.0K  488K   1% /dev
udev                               1.9G     0  1.9G   0% /dev/fuse
tmpfs                              100K     0  100K   0% /dev/lxd
tmpfs                              100K     0  100K   0% /dev/.lxd-mounts
tmpfs                              2.0G     0  2.0G   0% /dev/shm
tmpfs                              394M  1.1M  393M   1% /run
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs                              1.0M     0  1.0M   0% /var/snap/lxd/common/ns
tmpfs                              394M     0  394M   0% /run/user/1000

So, what am I doing wrong?

**Comment by evilnick** [comment]
are you using zfs?

**Comment by MatthijsKrempel** [comment]
No, I selected "dir", like stated in the installation instruction.

**Comment by evilnick** [comment]
okay. Can I ask for more details on the system you are running on? Like cpu, OS

**Comment by MatthijsKrempel** [comment]
AMD64, 32 Gb RAM, Windows 10 in a Hyper-V VM.

**Comment by evilnick** [comment]
Okay, that is useful to know. The other similar problem I've come across in the past is cgroups not being enabled in the kernel of the host OS. I think this is beyond 'the instructions are wrong' except possibly in terms of mentioning prerequisites. I am going to open a bug against Charmed Kubernetes rather than just the docs (I will link it here) for more developer eyeballs.

**Comment by evilnick** [comment]
Bug report here if you want to track it or add any info <https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1922761>
Sorry you couldn't get it working - I heavily suspect that it is something to do with the VM environment but at the very least we may come up with a workaround and a note to add to the docs

**Comment by MatthijsKrempel** [comment]
Thanks Nick, wil keep an eye on this.

**Comment by MatthijsKrempel** [comment]
> Bug report here if you want to track it or add any info https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1922761
> Sorry you couldn't get it working - I heavily suspect that it is something to do with the VM environment but at the very least we may come up with a workaround and a note to add to the docs

The suggested change seems to fix the issue, might want to add it to the docs.

**Comment by evilnick** [comment]
Great, thanks for taking the time to confirm this works. I will add a notice about the bug to the local install page
