### ISSUE TITLE
Upgrade to 1.19 docs incorrect

### ISSUE THREAD

**Issue by addyess** [charmed-kubernetes/kubernetes-docs#570]
https://ubuntu.com/kubernetes/docs/1.19/upgrading

there are various sections which show changing the `channel=1.20/stable` or `channel=1.12/stable`

Since this document is about upgrading to 1.19 these should all state 
```bash
juju config kubernetes-master channel=1.19/stable
```

and

```bash
juju config kubernetes-worker channel=1.19/stable
```

**Comment by evilnick** [comment]
hi, i believe this was resolved by recent updates

**Comment by addyess** [comment]
Maybe i'm missing something.  Was the page updated b/c it still seems this site doesn't reflect those changes:

https://ubuntu.com/kubernetes/docs/1.19/upgrading

search for:
```bash
juju config kubernetes-master channel=1.20/stable
```

```bash
juju config kubernetes-worker channel=1.12/stable
```

```bash
juju config kubernetes-worker channel=1.12/stable
```

**Comment by addyess** [comment]
Looks like this commit should have taken care of it.  Not sure how the site gets repopulated
https://github.com/charmed-kubernetes/kubernetes-docs/commit/f3107d3c04f1caaf8a2af0f39fa061bc342c098c#diff-5d7ab5a33773c30adc946eb2d0590e86dbfbbd5080ba000c865527b7f3ec6011

**Comment by evilnick** [comment]
Yeah, I will check into why this hasn't synced with the published docs. I think it is just waiting on ubuntu.com to get refreshed

**Comment by evilnick** [comment]
Apologies for this, I found the issue, should get refreshed sometime today
