### ISSUE TITLE
Docs of local CDK deployment

### ISSUE THREAD

**Issue by ktsakalozos** [charmed-kubernetes/kubernetes-docs#59]
Just spent a few hours helping a friend on #kubernetes-users and I also see a second user having trouble with this.

Users start with  https://kubernetes.io/docs/getting-started-guides/ubuntu/local/ on 18.04. 

 - The guide says "Note: If conjure-up asks you to “Setup an IPv6 subnet” with LXD, answer NO. IPv6 with Juju/LXD is currently unsupported. If you already have a bridge configured, e.g. lxdbr0, disable IPv6 on the bridge, otherwise you won’t be able to choose it." I did never see that, instead it was not giving you the option to deploy on localhost.
 - Conjure-up tell you "Unable to find IPv4-only network bridge for LXD. For information on configuring networking for LXD, see https://docs.conjure-up.io/devel/en/#users-of-lxd" however the right link should have been "https://docs.conjure-up.io/devel/en/user-manual#users-of-lxd". 
 - "https://docs.conjure-up.io/devel/en/user-manual#users-of-lxd" gives you all the info you need in a rather convoluted way. Instead it should tell you to: `sudo snap install lxd`, `/snap/bin/lxd init` select dir for storage and no ipv6 support and then `sudo /snap/bin/lxd.migrate` (if this migration fails do a `sudo apt-get purge lxc*` and `sudo apt-get purge lxd*`)
 - GPU support on localhost is problematic/unsupported. The user should be told to "Configure" kubernetes-worker -> Show Advance Configuration -> set "docker_runtime" to "apt". If possible conjure-up should handle this transparently.

I see we also have two more pages with localhost instructions: https://github.com/juju-solutions/kubernetes-docs/blob/master/pages/k8s/install-local.md and https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Deploying-on-LXD

**Comment by evilnick** [comment]
Thanks for this I will take a look through.

First off though, shouldn't we replace the upstream docs with a pointer to the real docs?

**Comment by evilnick** [comment]
@tvansteenburgh is there any special procedure for updating the upstream docs? ^

**Comment by evilnick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Edit docs on upstream kubernetes.io to point to new official docs.](https://trello.com/c/HbOdSgCB/61-edit-docs-on-upstream-kubernetesio-to-point-to-new-official-docs)

**Comment by tvansteenburgh** [comment]
@evilnick There's no special procedure, just PRs against the kubernetes.io website repo.
