### ISSUE TITLE
need a section for azure gpu workers

### ISSUE THREAD

**Issue by kwmonroe** [charmed-kubernetes/kubernetes-docs#593]
We discuss GPU workers on AWS and GCP here:

https://ubuntu.com/kubernetes/docs/gpu-workers

But not Azure. We should figure out what instance-types are necessary to document how to add GPU workers on Azure.

**Comment by evilnick** [comment]
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup may be useful in this context
