### ISSUE TITLE
Remove `p-notification__action` from the feedback notification

### ISSUE THREAD

**Issue by anthonydillon** [charmed-kubernetes/kubernetes-docs#620]
The `p-notification__action` class adds extra padding to the left side of the link. It is designed for single actions.

![image](https://user-images.githubusercontent.com/1413534/145260166-2f3ab786-c52d-4265-b41d-b08b19cf9597.png)

**Comment by evilnick** [comment]
@anthonydillon ^ does just removing it as per this PR fix it for you?
