### ISSUE TITLE
charm configuration table doesn't render well for 1.23

### ISSUE THREAD

**Issue by kwmonroe** [charmed-kubernetes/kubernetes-docs#628]
Looks like there are some newlines in 1.23 charm configuration tables that break the table rendering.  E.g.:

https://ubuntu.com/kubernetes/docs/1.23/charm-kubernetes-master#configuration
https://ubuntu.com/kubernetes/docs/1.23/charm-kubernetes-worker#configuration

In 1.22, the configuration table [didn't have newlines between rows](https://raw.githubusercontent.com/charmed-kubernetes/kubernetes-docs/master/pages/k8s/1.22/charm-kubernetes-master.md). In 1.23, [it does](https://raw.githubusercontent.com/charmed-kubernetes/kubernetes-docs/master/pages/k8s/1.23/charm-kubernetes-master.md).

**Comment by evilnick** [comment]
This is very weird and I'm pretty sure these pages looked okay, but I think I made the PR at 4am or something, so maybe my eyes were blurry. Doesn't seem hard to fix
