### ISSUE TITLE
kubernetes-e2e no longer available as validation tool

### ISSUE THREAD

**Issue by mastier** [charmed-kubernetes/kubernetes-docs#634]
As charmstore (jaas.ai) is switched to charmhub.io now there's no kubernetes-e2e charm.

The whole validation is a subject to change
https://github.com/charmed-kubernetes/kubernetes-docs/blob/4411dc1f19b65b36e476eab087f3be6419f019e4/pages/k8s/validation.md

That tools is mentioned in the official docs 
https://ubuntu.com/kubernetes/docs/validation

**Comment by evilnick** [comment]
the kubernetes-e2e charm does still exist and is still deployable following the instructions given

```
juju deploy cs:~containers/kubernetes-e2e
```

redirects to charmhub.

There may be a question about the validity of the e2e tests, but they run as described
