### ISSUE TITLE
Bundle links broken

### ISSUE THREAD

**Issue by jblesener** [charmed-kubernetes/kubernetes-docs#643]
It might be due to the [Charm Store to CharmHub migration](https://discourse.charmhub.io/t/charmhub-transition-faq/5636) but all of the bundle.yaml links in the docs are broken/returning a 404.

Example: https://ubuntu.com/kubernetes/docs/1.23/release-notes - https://api.jujucharms.com/charmstore/v5/charmed-kubernetes-862/archive/bundle.yaml

Other pages:
https://ubuntu.com/kubernetes/docs/1.22/release-notes
https://ubuntu.com/kubernetes/docs/1.21/release-notes
https://ubuntu.com/kubernetes/docs/install-manual
https://ubuntu.com/kubernetes/docs/supported-versions

**Comment by addyess** [comment]
@jblesener, please see the above PR for more formal versions of the links until this is resolved

**Comment by evilnick** [comment]
This should be resolved now
