### ISSUE TITLE
Metallb deploy command in docs wrong

### ISSUE THREAD

**Issue by parsifallo** [charmed-kubernetes/kubernetes-docs#659]
Hey!
On page https://ubuntu.com/kubernetes/docs/metallb the metallb deploy commands needs to be updated to:

```
juju deploy containers-metallb
```

BR

**Comment by evilnick** [comment]
thanks for pointing this out. I don't think we are using the containers- prefix in charmhub longterm. The cs stuff was supposed to redirect to the relevant charm in charmhub, but that doesn't seem to be working properly.

**Comment by addyess** [comment]
Updated docs here: https://discourse.charmhub.io/t/metallb-controller-speaker-docs-index/6320
