### ISSUE TITLE
MetalLB page formatting is broken

### ISSUE THREAD

**Issue by cjohnston1158** [charmed-kubernetes/kubernetes-docs#679]
<img width="855" alt="Screen Shot 2022-05-10 at 14 55 27" src="https://user-images.githubusercontent.com/24707086/167738062-5cbfae62-3657-458c-ae31-29f5838b49a6.png">

**Comment by evilnick** [comment]
yeah, i saw that. thanks. Funnily it isn't broken on the preview -https://cdk-docs.netlify.app/kubernetes/docs/metallb
I think the m parser on u.c is a little odd, but thanks for mentioning it, it's on the list

**Comment by evilnick** [comment]
https://github.com/canonical-web-and-design/ubuntu.com/pull/11630 should fix it
