### ISSUE TITLE
using calico overlay with rev 1009 results in error since calico is already part of the base bundle

### ISSUE THREAD

**Issue by baycarbone** [charmed-kubernetes/kubernetes-docs#682]
The installation documentation should be updated to reflect that calico is now the CNI used in the base bundle.
https://ubuntu.com/kubernetes/docs/install-manual

Specifically, the example provided does not work: `juju deploy charmed-kubernetes --overlay aws-overlay.yaml --trust --overlay calico-overlay.yaml
`

It results in this error:
```
juju deploy charmed-kubernetes --overlay aws-overlay.yaml --trust --overlay calico-overlay.yaml
Located bundle "charmed-kubernetes" in charm-hub, revision 1009
ERROR cannot deploy bundle: the provided bundle has the following errors:
relation ["calico:etcd" "etcd:db"] is defined more than once
relation ["calico:cni" "kubernetes-control-plane:cni"] is defined more than once
relation ["calico:cni" "kubernetes-worker:cni"] is defined more than once
```

**Comment by evilnick** [comment]
thanks

**Comment by evilnick** [comment]
There is a fix for this already in these docs - see https://cdk-next.netlify.app/kubernetes/docs/install-manual
it just hasn't been published on ubuntu.com, so I am going to close this, but many thanks for submitting the issue
