### ISSUE TITLE
Upgrade notes "Upgrade to 1.24" link is a button

### ISSUE THREAD

**Issue by Cynerva** [charmed-kubernetes/kubernetes-docs#686]
I'm seeing a weirdly formatted "Upgrade to 1.24" link button in the upgrade-notes page: https://ubuntu.com/kubernetes/docs/upgrade-notes

![upgrade-1 24-weird-format](https://user-images.githubusercontent.com/2251600/169085231-73255073-0102-421d-a5ed-510912aedfd1.png)

Is it supposed to be a button? Looks kinda weird clipping the text around it, right?

**Comment by evilnick** [comment]
That is indeed weird. I shall investigate
