### ISSUE TITLE
kube-api-endpoint relation for OpenStack integration is in question

### ISSUE THREAD

**Issue by nobuto-m** [charmed-kubernetes/kubernetes-docs#687]
By having the relation, it looks like we are creating an SPOF in the deployment.
https://github.com/charmed-kubernetes/kubernetes-docs/blob/c2ea8a478a1a24ad867d36a4b57f8c3724758b66/pages/k8s/openstack-integration.md?plain=1#L176

Let's discuss in the following bug for the bundle and reflect changes into the doc if that's the right way.
https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1974280

ref.
https://github.com/charmed-kubernetes/bundle/pull/768
https://github.com/charmed-kubernetes/kubernetes-docs/pull/371

**Comment by Cynerva** [comment]
Agreed, since Charmed Kubernetes 1.22, that relation should not be established. I will remove it from the overlay in documentation.
