### ISSUE TITLE
docker2containerd not linking

### ISSUE THREAD

**Issue by cjohnston1158** [charmed-kubernetes/kubernetes-docs#698]
[this section of the upgrade notes][docker2containerd]

Seen on:
https://ubuntu.com/kubernetes/docs/1.24/upgrading
https://ubuntu.com/kubernetes/docs/upgrading

Should be an actual link

**Comment by evilnick** [comment]
Sorry, for some reason, in spite of at least two syncs with the published docs, this hasn't appeared live yet. I will have to look into why that is, but I will raise a separate PR for it in the meantime - thanks for the fix
