### ISSUE TITLE
MetalLB page is not rendering properly

### ISSUE THREAD

**Issue by Cynerva** [charmed-kubernetes/kubernetes-docs#709]
https://ubuntu.com/kubernetes/docs/metallb

Not sure what's going on there, but a lot of things aren't rendering properly in that page. Links, headings, and code blocks are all pretty broken.

**Comment by francismendes** [comment]
+1
And I would add that this page is a little outdated; it seems that the charm's page on metallb-speaker and metallb-controller has the right directions of how to set up MetalLB.
