### ISSUE TITLE
MetaLB page is not clear on bootstrapping juju on top of k8s

### ISSUE THREAD

**Issue by Basdbruijne** [charmed-kubernetes/kubernetes-docs#714]
On the metallb page: https://ubuntu.com/kubernetes/docs/metallb, its not clear how to bootstrap a juju controller on top of k8s when using metallb.

I assume its either:
```
juju add-k8s k8s-cloud --controller $(juju switch | cut -d: -f1)
juju add-model metallb-system k8s-cloud
juju deploy metallb
juju bootstrap k8s-cloud
```

or

```
juju add-k8s k8s-cloud --controller $(juju switch | cut -d: -f1)
juju bootstrap k8s-cloud
juju add-model metallb-system k8s-cloud
juju deploy metallb
```

**Comment by evilnick** [comment]
Hi, thanks for reporting this. I will review the page and see what can be done to clarify

In the meantime, you could take a look at https://ubuntu.com/kubernetes/docs/operator-charms which has info on using operator charms

N.B you dont need to bootstrap the k8s cloud
