### ISSUE TITLE
equinix docs example is outdated

### ISSUE THREAD

**Issue by addyess** [charmed-kubernetes/kubernetes-docs#724]
https://ubuntu.com/kubernetes/docs/equinix includes full bundle which doesn't use the equinox overlay.  
Please update the docs to give examples including the equinox overlay

**Comment by evilnick** [comment]
IS this one up to date? - https://github.com/charmed-kubernetes/bundle/blob/main/overlays/equinix-overlay.yaml

**Comment by addyess** [comment]
Updated with this 
* https://github.com/charmed-kubernetes/kubernetes-docs/pull/726
