### ISSUE TITLE
kubernetes-dashboard charm is missing from additional charms

### ISSUE THREAD

**Issue by cjohnston1158** [charmed-kubernetes/kubernetes-docs#753]
The [Additional charms](https://ubuntu.com/kubernetes/docs/1.26/components#additional-charms) section of the docs are missing the kubernetes-dashboard charm. I believe this is due to [get_charms()](https://github.com/charmed-kubernetes/kubernetes-docs/blob/main/generator/k8s_docs_tools/generate_release.py#L60) only grabbing charms listed in the charm-support-matrix, which kubernetes-dashboard has been removed from since the k8s team no longer maintains the charm.

**Comment by evilnick** [comment]
there has been some discussion  about what we call those sections and what gets included in them. No conclusions so far 
@addyess @kwmonroe any thoughts?

**Comment by kwmonroe** [comment]
Jolly good spot @cjohnston1158.  There are a few other issues with that components page; let's fix them all in #754.
