### ISSUE TITLE
Page titles do not include Kubernetes

### ISSUE THREAD

**Issue by lathiat** [charmed-kubernetes/kubernetes-docs#773]
Today I linked the following URL to someone:
https://ubuntu.com/kubernetes/docs/ceph

The preview in chat is simply the HTML title, which is only: "Ceph storage | Ubuntu"

This is a fairly inaccurate description, ideally it would at least say Kubernetes, or some more contextual information. While you could update the specific page title it seems perhaps pages should ideally inherit a section title or something automatically - at least by default.

**Comment by evilnick** [comment]
Sorry for not noticing this sooner. 
From a docs standpoint, the only thing we can influence is the 'title' element of the page, which is also the displayed title. For obvious reasons we choose not to include 'Kubernetes' in every actual title.  I don't disagree but I suspect the answer would be for the website to tack 'Kubernetes |' or whatever to the beginning of the contextual info.
