### ISSUE TITLE
Autoscaling docs - taint needs updating

### ISSUE THREAD

**Issue by VariableDeclared** [charmed-kubernetes/kubernetes-docs#781]
Hello

When following https://ubuntu.com/kubernetes/docs/autoscaler the taint in that doc is written as
```
kubectl taint node $NODE juju.is/kubernetes-control-plane=true:NoSchedule-
```
Although, it appears as of 1.27 this taint has changed, making the correct step to run:
```
kubectl taint node $NODE node-role.kubernetes.io/control-plane=true:NoSchedule-
```

Once I ran this above taint removal, I was able to schedule the autoscaler onto my control plane node,

Thanks!
Peter

**Comment by evilnick** [comment]
Cool, thanks for the update
