### ISSUE TITLE
missing PRs from u.c

### ISSUE THREAD

**Issue by kwmonroe** [charmed-kubernetes/kubernetes-docs#783]
Looks like the `main` and `current` branches are out of sync. #778 and #779 are missing from `main`, which i suspect is why they're missing from u.c. as well.  Afaict, those are the only 2 PRs missing, but may be worth a deeper dive into the branch histories.

**Comment by evilnick** [comment]
yes, I noticed that myself when i was following up on some link snafus. shouldn't be hard to fix
