### ISSUE TITLE
correct cmd line for backup "juju run etcd/0 snapshot keys-version=v3" 

### ISSUE THREAD

**Issue by zhanglei-mao** [charmed-kubernetes/kubernetes-docs#807]
For https://ubuntu.com/kubernetes/docs/backups,  it should be etcd actions not run.   
so I guess you mean: "juju run-action etcd/0 snapshot keys-version=v3 --wait"  
instead of "juju run etcd/0 snapshot keys-version=v3"

**Comment by evilnick** [comment]
No, this command was changed from Juju 3.0

**Comment by zhanglei-mao** [comment]
Thanks. My Juju is still 2.9.45.
