### ISSUE TITLE
charmed and monitoring

### ISSUE THREAD

**Issue by cnu80** [charmed-kubernetes/kubernetes-docs#822]
Hi, we are deploying charmed in our infrastructure, and now we are confused how to add monitoring.

Under: https://ubuntu.com/kubernetes/docs/monitoring 
the overlay bundle is mentioned. 

From charmhub.io we found COS:
Under: https://ubuntu.com/server/docs/logging-monitoring-alerting
The LMA stack is being succeeded by COS. 

What is the correct way to add features to charmed. With overlay files or with juju and charmhub ?

Thanks

**Comment by evilnick** [comment]
Both are correct - you can do either. Overlays are more convenient if it is something you may repeat because you can save the overlay and re-use them.

N.B. The COS stack isn't supported until the 1.29 release (due imminently)
