### ISSUE TITLE
LDAP documentation got broken link

### ISSUE THREAD

**Issue by mastier** [charmed-kubernetes/kubernetes-docs#844]
If you try go to the link "[LDAP and Keystone with Charmed **Kubernetes](https://github.com/charmed-kubernetes/kubernetes-docs/blob/main/kubernetes/docs/ldap)."** in the following document:
 https://github.com/charmed-kubernetes/kubernetes-docs/blob/main/pages/k8s/auth.md#managing-users-with-an-external-service

You will get 404
![image](https://github.com/charmed-kubernetes/kubernetes-docs/assets/1609672/8746a690-7622-4807-a49b-416e6d486b3e)

I bet you meant 
https://github.com/charmed-kubernetes/kubernetes-docs/blob/main/pages/k8s/ldap.md

**Comment by addyess** [comment]
@mastier i'd recommend you not use github to browse the docs:

Perhaps the page you were looking for from https://ubuntu.com/kubernetes/docs/auth is this one https://ubuntu.com/kubernetes/docs/ldap?  The links should all be correct from there. 

this repo is the SOURCE material for what is published at https://ubuntu.com/kubernetes/docs

**Comment by mastier** [comment]
Ack. Still it would be nice if those were aligned.

**Comment by addyess** [comment]
@mastier maybe i wasn't following the original ask on this issue. Please allow me to ask a further question:

You are stating that the links in the markdown which do not end with an `.md` yeilds broken links while viewing these docs sources on  github?  Did i understand you wished that every link in this source repo included the `.md`? 

When these pages are rendered for presentation on ubuntu.com, they links are correct.  Do you have a suggestion for how to align the links?

cc: @evilnick

**Comment by mastier** [comment]
Ok. My bad then i was advised by Perk to look at the docs in github. Then I falsely assumed they are browseable.

You are right around .md and non md handling urls. I have not idea how to solve that properly :-)

**Comment by addyess** [comment]
I think @perk just didn't provide you an appropriate link to the published docs.  Navigating the github is like navigating source code -- the answers are there -- but less clear than looking at the rendered docs.  Let's stick to the published docs anyway.  Thanks so much
