### ISSUE TITLE
wrong instruction in https://ubuntu.com/kubernetes/docs/how-to-cos-lite

### ISSUE THREAD

**Issue by zilardcherry** [charmed-kubernetes/kubernetes-docs#846]
In this document:  https://ubuntu.com/kubernetes/docs/how-to-cos-lite

This line is redundant and might be only valid if customer installed k8s using the k8s machine charm https://charmhub.io/k8s
juju integrate grafana-agent:cos-agent k8s:cos-agent

So this:
juju integrate grafana-agent:cos-agent k8s:cos-agent

is basically redundant with that one:
juju integrate grafana-agent:cos-agent kubernetes-control-plane:cos-agent

And as a conclusion this: "juju integrate grafana-agent:cos-agent k8s:cos-agent" should be removed

After the customer deploys Charmed Kubernetes: https://charmhub.io/charmed-kubernetes
he will get kubernetes-control-plane and kubernetes-worker
and only these 2 lines should remain in the document:

juju integrate grafana-agent:cos-agent kubernetes-control-plane:cos-agent
juju integrate grafana-agent:cos-agent kubernetes-worker:cos-agent

Many thanks,
Szilard

**Comment by evilnick** [comment]
Thanks for taking the time to report this
pinging @mateoflorido @kwmonroe @eaudetcobello in case this doc needs a wider review ?

**Comment by addyess** [comment]
Does this PR change address the issue
https://github.com/charmed-kubernetes/kubernetes-docs/pull/843/files#diff-3377ce743d42a287d2fc236541ff8a468083cf895583f375bdf3b692d34b9d97

**Comment by zilardcherry** [comment]
@addyess Yes, I think so,  although my charmed kubernetes deployment contains only 1 kubernetes-control-plane unit and 1 kubernetes-worker, for simplicity,  so I didn't try this part "juju integrate grafana-agent:cos-agent kubeapi-load-balancer:cos-agent"

@addyess  you wrote in the PR change => "i'm sure the original author mistakenly wrote here."   and yes you're right, that's the main problem here, hence why this "juju integrate grafana-agent:cos-agent k8s:cos-agent"  line  needs to be removed

Probably the author based this article initially on the k8s machine  charm,  and the later the author re-wrote /  adapted the article to charmed kubernetes, but forgot to remove the line related to k8s:cos-agent

Afaik, the k8s machine charm basically deploys a kubernetes control-plane node  [https://charmhub.io/k8s]
and there's also another charm calleed k8s-worked [https://charmhub.io/k8s-worker]  which deploys  the kubernetes worker node
but these 2 charms are completely different from charmed-kubernetes https://charmhub.io/charmed-kubernetes

**Comment by addyess** [comment]
Yep... this is what happened. 

@charmed-kubernetes/canonical-k8s-team maintains all these charms, and it was a doc mistake to add the `k8s` charm into the mix.  Sorry for the confusion and nice to see you found the same problem we did.
