### ISSUE TITLE
k8s 1.30 is missing

### ISSUE THREAD

**Issue by aborsik** [charmed-kubernetes/kubernetes-docs#853]
As is stated here https://ubuntu.com/about/release-cycle#canonical-kubernetes-release-cycle k8s 1.30 is supported from April 2024. So far, there is no mention here: https://ubuntu.com/kubernetes/docs/supported-versions, nor anything like release notes, bundle, ..

Could you please add it there? Thank you.

**Comment by evilnick** [comment]
The actual release of Charmed Kubernetes was delayed due to various QA issues. It is now released and the documentation is up to date, sorry for the misleading info on the releases site.
