### ISSUE TITLE
Add docker info to updates page

### ISSUE THREAD

**Issue by evilnick** [charmed-kubernetes/kubernetes-docs#95]
There currently isn't any guidance on how to update the version of docker running in CDK

**Comment by hyperbolic2346** [comment]
juju ssh $unit "sudo DEBIAN_FRONTEND=noninteractive apt-get install -y $package --allow-change-held-packages -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' && sudo service docker restart"

**Comment by Cynerva** [comment]
> sudo service docker restart

I believe this will restart all the Docker containers. Users need to be warned about this.

**Comment by evilnick** [comment]
wouldn't I be better doing:

juju run --application=kubernetes-worker "sudo DEBIAN_FRONTEND=noninteractive apt-get install -y $package --allow-change-held-packages -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' && sudo service docker restart"

**Comment by hyperbolic2346** [comment]
@Cynerva certainly. This is a thing that will disrupt for sure. Official docs will most likely include a cordon and drain.

**Comment by hyperbolic2346** [comment]
@evilnick Only if you are cool with all of them stopping handling workloads at the same time and you were really sure the upgrade was going to work. I think pushing a machine or two at a time and allowing the cluster to recover is the better option.
